export enum Collections {
  WORKSPACE = "workspace",
  USER = "user",
  TEAM = "team",
  PLAN = "plan",
  COLLECTION = "collection",
  EARLYACCESS = "earlyaccess",
  ENVIRONMENT = "environment",
  FEATURES = "features",
  BRANCHES = "branches",
  FEEDBACK = "feedback",
  UPDATES = "updates",
  CHATBOTSTATS = "chatbotstats",
  TESTFLOW = "testflow",
  USERINVITES = "userinvites",
  AILOGS = "ailogs",
  USERLIMITLOGS = "userlimitlogs",
}
