export enum SUBSCRIPTION {
  USER_ADDED_TO_TEAM_SUBSCRIPTION = "USER_ADDED_TO_TEAM_SUBSCRIPTION",
  USER_REMOVED_FROM_TEAM_SUBSCRIPTION = "USER_REMOVED_FROM_TEAM_SUBSCRIPTION",
  CREATE_USER_SUBSCRIPTION = "CREATE_USER_SUBSCRIPTION",
  TEAM_ADMIN_ADDED_SUBSCRIPTION = "TEAM_ADMIN_ADDED_SUBSCRIPTION",
  TEAM_ADMIN_DEMOTED_SUBSCRIPTION = "TEAM_ADMIN_DEMOTED_SUBSCRIPTION",
  UPDATES_ADDED_SUBSCRIPTION = "UPDATES_ADDED_SUBSCRIPTION",
  AI_RESPONSE_GENERATED_SUBSCRIPTION = "AI_RESPONSE_GENERATED_SUBSCRIPTION",
  TEAM_DETAILS_UPDATED_SUBSCRIPTION = "TEAM_DETAILS_UPDATED_SUBSCRIPTION",
  AI_LOGS_GENERATOR_SUBSCRIPTION = "AI_LOGS_GENERATOR_SUBSCRIPTION",
}
