export enum SUBSCRIPTION {
  USER_ADDED_TO_TEAM_SUBSCRIPTION = "USER_ADDED_TO_TEAM_SUBSCRIPTION",
  USER_CREATED_SUBSCRIPTION = "USER_CREATED_SUBSCRIPTION",
  TEAM_OWNER_ADDED_SUBSCRIPTION = "TEAM_OWNER_ADDED_SUBSCRIPTION",
  USER_REMOVED_FROM_TEAM_SUBSCRIPTION = "USER_REMOVED_FROM_TEAM_SUBSCRIPTION",
  CREATE_USER_SUBSCRIPTION = "CREATE_USER_SUBSCRIPTION",
}
