export enum UpdatesType {
  WORKSPACE = "workspace",
  COLLECTION = "collection",
  FOLDER = "folder",
  REQUEST = "request",
  ROLE = "role",
  ENVIRONMENT = "environment",
  TESTFLOW = "testflow",
  WEBSOCKET = "websocket",
  SOCKETIO = "socketio",
  GRAPHQL = "graphql",
  REQUEST_RESPONSE = "request_response",
  MOCK_REQUEST = "mock_request",
  MOCK_REQUEST_RESPONSE = "mock_request_response",
  AI_REQUEST = "ai_request",
}
