import { ApiProperty } from "@nestjs/swagger";
import { IsNotEmpty, IsOptional, IsString } from "class-validator";

/**
 * Data Transfer Object for AI response.
 */
export class AIResponseDto {
  /**
   * The result generated by the AI.
   * @example ["hii"]
   */
  @IsNotEmpty()
  @ApiProperty({
    required: true,
    example: ["hii"],
  })
  result: string;

  /**
   * The thread ID associated with the response.
   * @example "thread_34789"
   */
  @ApiProperty({
    required: true,
    example: "thread_34789",
  })
  @IsNotEmpty()
  threadId: string;

  /**
   * The message ID associated with the response.
   * @example "msg_34789"
   */
  @ApiProperty({
    required: true,
    example: "msg_34789",
  })
  @IsNotEmpty()
  messageId: string;
}

/**
 * Data Transfer Object for generating AI response.
 */
export class PromptPayload {
  /**
   * The prompt or command.
   */
  @IsString()
  @ApiProperty({ required: true, example: "prompt" })
  @IsNotEmpty()
  text: string;

  /**
   * The thread ID associated with the prompt.
   */
  @IsString()
  @IsOptional()
  @ApiProperty({ required: true, example: "thread id" })
  threadId: string;

  /**
   * Additional instructions for the assistant which will
   * decide the context for a particular thread.
   */
  @IsString()
  @IsOptional()
  @ApiProperty({ required: true, example: "instructions to your assistant" })
  instructions: string;
}

/**
 * Data Transfer Object for generating AI response.
 */
export class StreamPromptPayload {
  /**
   * The prompt or command.
   */
  @IsString()
  @ApiProperty({ required: true, example: "prompt" })
  @IsNotEmpty()
  text: string;

  /**
   * The thread ID associated with the prompt.
   */
  @IsString()
  @IsOptional()
  @ApiProperty({ required: true, example: "thread id" })
  threadId: string;

  /**
   * The tab id where that thread belongs.
   */
  @IsString()
  @IsNotEmpty()
  @ApiProperty({ required: true, example: "tab id" })
  tabId: string;

  /**
   * Additional instructions for the assistant which will
   * decide the context for a particular thread.
   */
  @IsString()
  @IsOptional()
  @ApiProperty({ required: true, example: "instructions to your assistant" })
  instructions: string;
}
